actors = None

items = None

exits = {
'1': ('warrens', 1, 'cave'),
'2': ('ancient_shrine', 1, 'castle'),
'3': ('bandit_keep', 1, 'castle'),
'4': ('sanctum', 1, 'castle'),
'5': ("haunt", 1, 'cave'),
'6': ('badbog', 1, 'cave'),
'7': ('vierfort', 1, 'village'),
'8': ('rage_hill', 1, 'cave'),
'9': ('red_outpost', 1, 'castle'),
'a': ('north_warren', 1, 'village'),
'b': ('mirefield_keep', 1, 'castle'),
'c': ('beggars_hole', 1, 'cave'),
'd': ('black_hollow', 1, 'village'),
'e': ('cindemere', 1, 'village')
}

vault_layouts = [
[
'################################################################################',
'#   TTT       ttttt     ttt     t ttt     tttTTTTTTTTttt  tttttttt    ttt  tTTT#',
'# @  TTT  a                                  ttTTTTTTT      ttttt      ~~~~~~ t#',
'#      TT                  TTTTTTT          tttttTTTTTttt     tt     ~~~~~~    #',
'#TTTT   T     ~~~         TTTTTTTTTTTT      ttTTTTTTt  t                ~~  3  #',
'#tttTT         ~~~       TTTTt   TTT       tTTTTTtt         ttt               t#',
'#t   TTT      ~~       TTTTttt 2              ttt            tt              tt#',
'#t 1 tTT           tt TTTTTTTt                                                t#',
'#t              ttttt   TTTTTTTTTtttt             t     tt       tt    tt    tt#',
'#ttt~~~      tttttt      TTTTTTTTTTTTTtttttt    tttt   ttttt    tttt  ttttttttt#',
'#~~~~~                   TTTTT                tttt               ttt         tt#',
'#  ~~~~~~             TTTTTTTTTT             TTTTT                ttt      d  t#',
'#     ~~~~              TTTTTTT            tTTTTTt c               ttttt       #',
'#                      TTTTTTT              tTTTTT                    ttttttttt#',
'#         #             TTTTTT              ttTTTttt                ~~~tttttttt#',
'#       ######           TTTTTTT              tTTTTTTTTtt          ~~~~~~tttttt#',
'#     #######              TTTTTTT             tTTTTTTTTTTTt      ~~  ~~~~~  tt#',
'#       ########                                 tTTTTTTTTTTT    ~~tt    ~~~~~t#',
'#        #   #####             ###               TTTTTTTTTTtt   ~~TTt      ~~~~#',
'#             ##              ###                 tTTTTTTtt     ~~Tt  6   tt   #',
'#          #####                                    tTTTTTTT    ~~t      tt    #',
'#        ####                      ###                tttt      ~~             #',
'#                                 #####                        ~~~             #',
'#                      ~~~~~~       ###   ~~~~~~~~            ~~~           ## #',
'#     ~~~~~~~~       ~~~~~~~~~~b        ~~~~~~~~~~~     ~~~~~~~~           #####',
'#~~~~~~~~~~~~~~~~~~~~~~tttttt~~~~~~  ~~~~      TT~~         ~~            #### #',
'#~~~~~tttttttt~~~~~~~~tttTTTTTttt~~  ~~         TT~~~       ~~           ##### #',
'#TTtttttTTTTTtttttttttttTTTTTtttt               TT  ~~~~   ~~~          ########',
'#TTTTTTTTTTTTTTTTTTTTTTTTTTTtttt                T      ~~~~~             #######',
'#TTTTT    TTTTTTTTTTTTTTTttttt          TTTTTT          ~~~               ######',
'#TT                                   TTTTT                                #####',
'#TTT  4          TTTTTttttt         TTT                 TTTTTT            ######',
'#TTTT    TTTTTTTTTTttttt             TTT 5            TTTTTTTTTTT          #####',
'#TTTTTTTTTTTTTTTTTtt~~~                                 ##TTTTT             ####',
'#TTTTTTTTTtttt  tt~~~~~~                              ######                  ##',
'#TTTTTTTt      ~~~~~~~~~~                             TT#####                  #',
'#TTTTTtttt   ~~~~~~~~~~~~~~~~~~                      TTTTT###                  #',
'#TTtttt  ~~~~~~~~~~~~~~~~~~~~~~~~~~                    TT####                  #',
'#ttttt        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             ##8                  #',
'#tt         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~       ###        ~~~      #',
'#         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          ####     ~~~~~~~~~~  #',
'#      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                            ~~~~~    #',
'#         ~~~~~~~~~~~~~~~~~~~~~~~                                    ~~~~      #',
'#          ~~~~~~~~~~~~~~~~~~~~~~~~~                                           #',
'#       tt    ~~~~~~~~~~~~~~~~~                                                #',
'#       TTTTT ~~~~~~~~~~~~~~                                                   #',
'#    ttTTTtt ~~~~~~~~~~~~~~~~          e                      ttt             ##',
'#    tTTTTTt    ~~~~~~~~~~~~~                              ttTTTTTT          ###',
'#  ttt           ~~~~~~~~~~~~                            tTTTTTTTTTT        ####',
'#    t              ~~~~~~~~~~                         tTTTTTTTTtt         #####',
'#       TT        7  ~~~~~~~                           TTTTTTTtt         #######',
'#      TTTT         ~~~~~~~                             tTTTTTT        #########',
'#     TTTTtt         ~~~~~~                ~~            tttTTTT    #  #########',
'#       TTTTT          ~~~                ~~~~~            TTTTTT  ##       ####',
'#t     TTTTTTT    ttt  ~~                   ~~~             tttt   ###        ##',
'#tt       TTTT     tt  ~    t              ~~~~~~                 ####      9 ##',
'#tttt     tTTT             tttt              ~~~~~~~             #####  ###   ##',
'#tt      TTT             tttt                  ~~             ##################',
'#ttttttt                ttttttt                            #####################',
'################################################################################']]